EatMoreFood/food/entries/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
urlpatterns = [
    path('', views.index, name='index'),
    path('home/', views.home, name='home'),
    path('added/', views.added, name='added'),
    path('add/', views.add, name='add'),
    path('past/', views.past, name='past'),
]

EatMoreFood/food/food/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import url,include
from mpjct import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('entries/', include('entries.urls')),
    url(r'^$',views.index,name='index'),
    url(r'^special/',views.special,name='special'),
    url(r'^mpjct/',include('mpjct.urls')),
    url(r'^logout/$', views.user_logout, name='logout'),
]

EatMoreFood/food/mpjct/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import url
from mpjct import views
from . import views

app_name = 'mpjct'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('dashboard/', views.dashboard, name='dashboard'),
    path('add/', views.add, name='add'),
    path('home/', views.home, name='home'),
    path('', views.index, name='index'),
    url(r'^register/$',views.register,name='signup'),
    url(r'^user_login/$',views.user_login,name='user_login'),

]

EatMoreFood/food/entries/models.py
from django.db import models
from django.contrib.contenttypes.fields import GenericRelation


class NewFood(models.Model):
    name = models.CharField(max_length=20)
    rating = models.IntegerField(default=5)
    comments = models.TextField()
    date_added = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return 'ID#{}>'.format(self.id)

    class Meta:
            verbose_name_plural = 'newfoods'

EatMoreFood/food/mpjct/models.py
from django.db import models
from django.contrib.auth.models import User


class UserProfileInfo(models.Model):
    user_id = models.OneToOneField(User,on_delete=models.CASCADE)
    name = models.CharField(max_length=20)
    profile_pic = models.ImageField(upload_to='profile_pics', blank=True)

    def __str__(self):
        return self.user.name
    class Meta:
        verbose_name_plural = 'userprofiles'

EatMoreFood/food/entries/forms.py
from django import forms
from django.forms import ModelForm
from .models import NewFood
from django.utils import timezone


class NewFoodForm(ModelForm):
    class Meta:
        model = NewFood
        fields = ('name', 'rating', 'comments')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['name'].widget.attrs.update(
            {'class': 'form-control', 'placeholder': 'Food Name'})
        self.fields['rating'].widget.attrs.update({'class': 'ChoiceField'})
        self.fields['comments'].widget.attrs.update(
            {'class': 'form-control', 'placeholder': 'Comments'})

EatMoreFood/food/mpjct/forms.py
from django import forms
from mpjct.models import UserProfileInfo
from django.contrib.auth.models import User

class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())
    class Meta():
        model = User
        fields = ('username','password','email')
class UserProfileInfoForm(forms.ModelForm):
     class Meta():
         model = UserProfileInfo
         fields = ('name','profile_pic')

EatMoreFood/food/entries/views.py
from django.shortcuts import render, redirect
from .models import NewFood
from .forms import NewFoodForm


def index(request):
    newfoods = NewFood.objects.order_by('-date_posted')

    context = {'newfoods': newfoods}

    return render(request, 'entries/home.html', context)


def add(request):
    if request.method == 'POST':
        form = NewFoodForm(request.POST)

        if form.is_valid():
            form.save()
            return redirect('added')
    else:
        form = NewFoodForm()

    context = {'form': form}

    return render(request, 'entries/add.html', context)


def home(request):

    return render(request, 'entries/home.html')


def past(request):
    newfoods = NewFood.objects.order_by('-date_added')

    context = {'newfoods': newfoods}

    return render(request, 'entries/past.html', context)


def added(request):
    last_entry = NewFood.objects.latest('date_added')

    return render(request, 'entries/added.html', {'last_entry':last_entry})

EatMoreFood/food/mpjct/views.py
from django.shortcuts import render, redirect
from mpjct.forms import UserForm, UserProfileInfoForm
from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponseRedirect, HttpResponse
from django.urls import reverse
from django.contrib.auth.decorators import login_required


def dashboard(request):

    return render(request, 'mpjct/dashboard.html')


def index(request):
    return render(request, 'mpjct/index.html')


@login_required
def special(request):
    return HttpResponse("You are logged in !")


@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('index'))


def register(request):
    registered = False
    if request.method == 'POST':
        user_form = UserForm(data=request.POST)
        profile_form = UserProfileInfoForm(data=request.POST)
        if user_form.is_valid() and profile_form.is_valid():
            user = user_form.save()
            user.set_password(user.password)
            user.save()
            profile = profile_form.save(commit=False)
            profile.user = user
            if 'profile_pic' in request.FILES:
                print('found it')
                profile.profile_pic = request.FILES['profile_pic']
            profile.save()
            registered = True
        else:
            print(user_form.errors, profile_form.errors)
    else:
        user_form = UserForm()
        profile_form = UserProfileInfoForm()
    return render(request, 'mpjct/signup.html',
                  {'user_form': user_form,
                           'profile_form': profile_form,
                           'registered': registered})


def user_login(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(username=username, password=password)
        if user:
            if user.is_active:
                login(request, user)
                return HttpResponseRedirect(reverse('index'))
            else:
                return HttpResponse("Your account was inactive.")
        else:
            print("Someone tried to login and failed.")
            print("They used username: {} and password: {}".format(
                username, password))
            return HttpResponse("Invalid login details given")
    else:
        return render(request, 'mpjct/login.html', {})


def home(request):
    return render(request, 'entries/home.html')


def add(request):
    return render(request, 'entries/add.html')

EatMoreFood/food/entries/templates/_formhelpers.html
{% macro render_field(field) %}
  <dt>{{ field.label }}
  <dd>{{ field(**kwargs)|safe }}
  {% if field.errors %}
    <ul class=errors>
    {% for error in field.errors %}
      <li>{{ error }}</li>
    {% endfor %}
    </ul>
  {% endif %}
  </dd>
{% endmacro %}

EatMoreFood/food/entries/templates/entries/add.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="Add New Food">
    <meta name="author" content="Chris Asp">
{% block title %}
    <title>Add a New Food Exposure</title>
{% endblock %}
{% block styles %}

    <!-- Bootstrap core CSS -->
    <link href="{% static 'entries/bootstrap.min.css' %}" rel="stylesheet">
    <!-- Bootstrap theme -->
    <link href="{% static 'entries/bootstrap-theme.min.css' %}" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="{% static 'entries/theme.css' %}" rel="stylesheet">
    <link href="{% static 'bootstrap/wtf.html' %}" rel="stylesheet">

{% endblock %}
  </head>
{% block content %}
  <body>

        <nav class="navbar navbar-inverse navbar-fixed-top">
          <div class="container-fluid">
            <div class="navbar-header">
              <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
              </button>
              <a class="navbar-brand" href="#">Eat More Food</a>
            </div>
            <div id="navbar" class="navbar-collapse collapse">
              <ul class="nav navbar-nav navbar-right">
                <li><a href="{% url 'home' %}">Home</a></li>
                <li><a href="{% url 'add' %}">New</a></li>
                <li><a href="{% url 'past' %}">Dashboard</a></li>
                {# Some logic on what to display for last item#}
                {% if user.is_authenticated %}
                  <li><a href="{% url 'logout' %}">Logout</a></li>
                {% else %}
                  <li><a class="navbar-link" href="{% url 'mpjct:signup' %}">Signup</a></li>
                  <li><a class="navbar-link" href="{% url 'mpjct:user_login' %}">Login</a></li>
                {% endif %}
              </ul>
              <form class="navbar-form navbar-right">
                <input type="text" class="form-control" placeholder="Search...">
              </form>
            </div>
          </div>
        </nav>

<div class="container">
    <div class="container theme-showcase" role="main">
      <div class="jumbotron">
        <h2>Welcome Back, {{ user }}</h2>
        <h1>Add New Food</h1>
      </div>
    </section>
    <section class="section">
        <div class="container">
          <form method="POST" action="{% url 'add' %}">
                  {% csrf_token %}
                  <div class="field">
                      <div class="control">
                          {{ form.text }}
                          <form class="form-signin" method="POST" action="//">
                          <div class="form-group">
                            <h2>New Food</h2>
                            <label for="inputName" class="sr-only">Food Name</label>
                            <input type="text" name="name" class="form-control" placeholder="Food Name" maxlength="20" required="" id="id_name">
                          </div>
                          <div class="form-group">
                            <h2>Rating</h2>
                            <label for="rating" class="sr-only">Rating out of 5</label>
                            <input type="Integer" name="rating" value="5" placeholder="5" required="" id="id_rating"> 1-5
                          </div>
                          <div class="form-group">
                            <h2>Comment</h2>
                            <label for="comments" class="sr-only">Comments:</label>
                              <textarea name="comments" cols="10" rows="5" class="form-control" placeholder="Any troubles?" required="" id="id_comments"></textarea>
                          </div>
                          <button class="btn btn-lg btn-primary btn-block" type="submit">Add Food</button>
                        </form>
                      </div>
                  </div>

                  <div class="field is-grouped is-grouped-right">
                      <div class="control">
                        </div>
                  </div>
          </form>
          </div>

          </section>
          <footer class="footer">
          </footer>
      </body>

      </html>


    <!-- </div>
</div>
</body></html>
{% endblock %}

EatMoreFood/food/entries/templates/entries/added.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="description" content="New Food Added">
  <meta name="author" content="Chris Asp">
  {% block title %}
  <title>New Food Exposure Added</title>
  {% endblock %}
  {% block styles %}

  <!-- Bootstrap core CSS -->
  <link href="{% static 'entries/bootstrap.min.css' %}" rel="stylesheet">
  <!-- Bootstrap theme -->
  <link href="{% static 'entries/bootstrap-theme.min.css' %}" rel="stylesheet">

  <!-- Custom styles for this template -->
  <link href="{% static 'entries/theme.css' %}" rel="stylesheet">
  <link href="{% static 'bootstrap/wtf.html' %}" rel="stylesheet">

  {% endblock %}
</head>
{% block content %}

<body>

  <nav class="navbar navbar-inverse navbar-fixed-top">
    <div class="container-fluid">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="#">Eat More Food</a>
      </div>
      <div id="navbar" class="navbar-collapse collapse">
        <ul class="nav navbar-nav navbar-right">
          <li><a href="{% url 'home' %}">Home</a></li>
          <li><a href="{% url 'add' %}">New</a></li>
          <li><a href="{% url 'past' %}">Dashboard</a></li>
          {# Some logic on what to display for last item#}
          {% if user.is_authenticated %}
            <li><a href="{% url 'logout' %}">Logout</a></li>
          {% else %}
            <li><a class="navbar-link" href="{% url 'mpjct:signup' %}">Signup</a></li>
            <li><a class="navbar-link" href="{% url 'mpjct:user_login' %}">Login</a></li>
          {% endif %}
        </ul>
        <form class="navbar-form navbar-right">
          <input type="text" class="form-control" gplaceholder="Search...">
        </form>
      </div>
    </div>
  </nav>

  <div class="container">
    <div class="container theme-showcase" role="main">
      <div class="jumbotron">
        <h2>You Did It, {{ user }}!</h2>
        <h1>New Food Added</h1>
      </div>
      <div>Congratulations on taking another step forward in your health journey. <br>Your body thanks you.</div>
      <div>
        <h2><b>{{ last_entry.name }} </b>Added</h2>
        <h3><span class="text-muted">Rating: {{ last_entry.rating }}</span><br>
        <span class="text-muted">Comments: {{ last_entry.comments }}</span>
</h3>
      </div>
      <div class="content">
        <a href="{% url 'add' %}">Add new entry</a>
      </div>
</body>
</html>
{% endblock %}

EatMoreFood/food/entries/templates/entries/form.html
{% load static %}
{% extends "bootstrap/base.html" %}
{% import "bootstrap/wtf.html" as wtf %}

{% block title %}
WTForms
{% endblock %}

{% block content %}
<div class="container">
    <form method="POST" action="/">
       <dl>
       {{ wtf.quick_form(form)}}

        <input class="btn btn-primary" type="submit" value="Login">
        </dl>
    </form>
</div>
{% endblock %}

EatMoreFood/food/entries/templates/entries/home.html
{% load static %}
<!DOCTYPE html>
<html lang="en"><head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="Eat More Food Home">
    <meta name="author" content="Chris Asp">
{% block title %}
    <title>Home</title>
    {% endblock %}
    {% block styles %}

        <!-- Bootstrap core CSS -->
        <link href="{% static 'entries/bootstrap.min.css' %}" rel="stylesheet">
        <!-- Bootstrap theme -->
        <link href="{% static 'entries/bootstrap-theme.min.css' %}" rel="stylesheet">

        <!-- Custom styles for this template -->
        <link href="{% static 'entries/theme.css' %}" rel="stylesheet">
        <link href="{% static 'bootstrap/wtf.html' %}" rel="stylesheet">

    {% endblock %}
      </head>
    {% block content %}
  <body>

        <nav class="navbar navbar-inverse navbar-fixed-top">
          <div class="container-fluid">
            <div class="navbar-header">
              <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
              </button>
              <a class="navbar-brand" href="#">Eat More Food</a>
            </div>
            <div id="navbar" class="navbar-collapse collapse">
              <ul class="nav navbar-nav navbar-right">
                <li><a href="{% url 'home' %}">Home</a></li>
                <li><a href="{% url 'add' %}">New</a></li>
                <li><a href="{% url 'past' %}">Dashboard</a></li>
                {# Some logic on what to display for last item#}
                {% if user.is_authenticated %}
                  <li><a href="{% url 'logout' %}">Logout</a></li>
                {% else %}
                  <li><a class="navbar-link" href="{% url 'mpjct:signup' %}">Signup</a></li>
                  <li><a class="navbar-link" href="{% url 'mpjct:user_login' %}">Login</a></li>
                {% endif %}
              </ul>
              <form class="navbar-form navbar-right">
                <input type="text" class="form-control" gplaceholder="Search...">
              </form>
            </div>
          </div>
        </nav>

<div class="container">
    <div class="container theme-showcase" role="main">
      <div class="jumbotron">
        <h2>Welcome Back, {{ userprofileinfo.name }}{% for n in userprofiles %}{{ n.name }}{% endfor %}{{ user }}</h2>
        <h1>Home</h1>
      </div>
                    <div>Welcome back to Eat More Food and to your continued food journey. <br>Variety is the spice of life and the basis of good health.<br>We're thrilled to assist you in increasing your food variety.</div></br>
                  <div>
              <img src="https://cdn.pixabay.com/photo/2017/03/01/16/45/fruit-2109043__340.jpg" width="400" height="400" class="img-responsive" >

                    <h2><b>Rainbow Foods</b></h2>
                    <span class="text-muted"><h3>Harvard Medical School</h3></span>

              <span class="text-muted">Rainbow foods increase immunity new study finds.</span><br>
                    <span class="text-muted">Don't be left with a cold this winter.</span>

</div></body></html>
{% endblock %}

EatMoreFood/food/entries/templates/entries/past.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="description" content="Food App Dashboard">
  <meta name="author" content="Chris Asp">
  {% block title %}
  <title>Eat More Food App Dashboard</title>
  {% endblock %}
  {% block styles %}

  <!-- Bootstrap core CSS -->
  <link href="{% static 'entries/bootstrap.min.css' %}" rel="stylesheet">
  <!-- Bootstrap theme -->
  <link href="{% static 'entries/bootstrap-theme.min.css' %}" rel="stylesheet">

  <!-- Custom styles for this template -->
  <link href="{% static 'entries/theme.css' %}" rel="stylesheet">
  <link href="{% static 'bootstrap/wtf.html' %}" rel="stylesheet">

  {% endblock %}
</head>
{% block content %}

<nav class="navbar navbar-inverse navbar-fixed-top">

  <div class="container-fluid">

    <div class="navbar-header">

      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">

        <span class="sr-only">Toggle navigation</span>

        <span class="icon-bar"></span>

        <span class="icon-bar"></span>

        <span class="icon-bar"></span>

      </button>

      <a class="navbar-brand" href="#">Eat More Food</a>

    </div>

    <div id="navbar" class="navbar-collapse collapse">

      <ul class="nav navbar-nav navbar-right">
        <li><a href="{% url 'home' %}">Home</a></li>
        <li><a href="{% url 'add' %}">New</a></li>
        <li><a href="{% url 'past' %}">Dashboard</a></li>
        {# Some logic on what to display for last item#}
        {% if user.is_authenticated %}
          <li><a href="{% url 'logout' %}">Logout</a></li>
        {% else %}
          <li><a class="navbar-link" href="{% url 'mpjct:signup' %}">Signup</a></li>
          <li><a class="navbar-link" href="{% url 'mpjct:user_login' %}">Login</a></li>
        {% endif %}
      </ul>
      <form class="navbar-form navbar-right">

        <input type="text" class="form-control" placeholder="Search...">

      </form>

    </div>

  </div>

</nav>


<div class="container">
  <div class="container theme-showcase" role="main">
    <div class="jumbotron">
      <h2>Welcome Back, {{ user }} {{ user.userprofileinfo.name }}</h2>
      <h1>Dashboard</h1>
    </div>
    <h1 class="page-header">Featured Foods</h1>



    <div class="row placeholders">

      <div class="col-xs-6 col-sm-3 placeholder">
        <h4>Last Entry</h4>
        <span class="text-muted">{{ last_entry.name }}
        <p><span class="text-muted">Rating: {{ last_entry.rating }}</span></p>
        <p><span class="text-muted">Comments: {{ last_entry.comments }}</span></p>

      </div>

      <div class="col-xs-6 col-sm-3 placeholder">
        <h4>Lowest Rated </h4>

        <span class="text-muted">{{ entry.name }}</span>
        <p><span class="text-muted">Rating: {{ entry.rating }}</span></p>
        <p><span class="text-muted">Comments: {{ entry.comments }}</span></p>
      </div>

      <div class="col-xs-6 col-sm-3 placeholder">


        <h4>First Eaten</h4>

        <span class="text-muted">{{ entry.name }}</span>
        <p><span class="text-muted">Rating: {{ entry.rating }}</span></p>
        <p><span class="text-muted">Comments: {{ entry.comments }}</span></p>

      </div>

      <div class="col-xs-6 col-sm-3 placeholder">

        <h4>Something New</h4>

        <span class="text-muted">Avocado</span>
        <p><span class="text-muted">Rating: ?</span></p>

      </div>

    </div>



    <h2 class="sub-header">Past Food Exposures</h2>

    <div class="table-responsive">

      <table class="table table-striped">

        <thead>

          <tr>

            <th>Name</th>

            <th>Rating</th>

            <th>Comments</th>

          </tr>

        </thead>

        <tbody>
{% for n in newfoods %}
          <tr>

            <td>{{ n.name }}</td>

            <td>{{ n.rating }}</td>

            <td>{{ n.comments }}</td>

          </tr>
{% endfor %}

        </tbody>

      </table>

    </div>

  </div>

</div>

</html>
{% endblock %}

EatMoreFood/food/mpjct/templates/_formhelpers.html
{% macro render_field(field) %}
  <dt>{{ field.label }}
  <dd>{{ field(**kwargs)|safe }}
  {% if field.errors %}
    <ul class=errors>
    {% for error in field.errors %}
      <li>{{ error }}</li>
    {% endfor %}
    </ul>
  {% endif %}
  </dd>
{% endmacro %}

EatMoreFood/food/mpjct/templates/bootstrap/base.html
{% block doc -%}
<!DOCTYPE html>
<html{% block html_attribs %}{% endblock html_attribs %}>
{%- block html %}
  <head>
    {%- block head %}
    <title>{% block title %}{{title|default}}{% endblock title %}</title>

    {%- block metas %}
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {%- endblock metas %}

    {%- block styles %}
    <!-- Bootstrap -->
    <link href="{{bootstrap_find_resource('css/bootstrap.css', cdn='bootstrap')}}" rel="stylesheet">
    {%- endblock styles %}
    {%- endblock head %}
  </head>
  <body{% block body_attribs %}{% endblock body_attribs %}>
    {% block body -%}
    {% block navbar %}
    {%- endblock navbar %}
    {% block content -%}
    {%- endblock content %}

    {% block scripts %}
    <script src="{{bootstrap_find_resource('jquery.js', cdn='jquery')}}"></script>
    <script src="{{bootstrap_find_resource('js/bootstrap.js', cdn='bootstrap')}}"></script>
    {%- endblock scripts %}
    {%- endblock body %}
  </body>
{%- endblock html %}
</html>
{% endblock doc -%}

EatMoreFood/food/mpjct/templates/mpjct/base.html
{% load static %}
<!DOCTYPE html>
<html>
  <head>
    <title>Eat More Food</title>
    <meta charset="utf-8">
    <!-- Latest compiled and minified CSS -->
    <link href="{% static 'entries/bootstrap.min.css' %}" rel="stylesheet">
    <!-- Bootstrap theme -->
    <link href="{% static 'entries/bootstrap-theme.min.css' %}" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="{% static 'entries/theme.css' %}" rel="stylesheet">
    <link href="{% static 'bootstrap/wtf.html' %}" rel="stylesheet">

   <!--<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous"> -->
<head>
  <body>
    <nav class="navbar navbar-default navbar-static-top">
      <div class="container">
        <ul class="nav navbar-nav">
          <li><a class="navbar-brand" href="{% url 'index' %}">Eat More Food</a></li>
          {# Some logic on what to display for last item#}
          {% if user.is_authenticated %}
            <li><a href="{% url 'logout' %}">Logout</a></li>
          {% else %}
            <li><a class="navbar-link" href="{% url 'mpjct:signup' %}">Signup</a></li>
            <li><a class="navbar-link" href="{% url 'mpjct:user_login' %}">Login</a></li>
          {% endif %}
</ul>
      </div>
    </nav>
    <div class="container">
    {% block body_block %}
    {% endblock %}
    </div>
  </body>
</html>

EatMoreFood/food/mpjct/templates/mpjct/form.html
from wtforms import Form, BooleanField, StringField, validators
{% extends "bootstrap/base.html" %}
{% import "bootstrap/wtf.html" as wtf %}

{% block title %}
WTForms
{% endblock %}

{% block content %}
<div class="container">
    <form method="POST" action="/">
       <dl>
       {{ wtf.quick_form(form)}}
        <input class="btn btn-primary" type="submit" value="Login">
        </dl>
    </form>
</div>
{% endblock %}

EatMoreFood/food/mpjct/templates/mpjct/index.html
{% extends "mpjct/base.html" %}
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="Eat More Food Index">
    <meta name="author" content="Chris Asp">
{% block title %}
    <title>Index</title>
    {% endblock %}
  </head>
      {% block body_block %}
      <div class="container">
        <div class="jumbotron">
          <h1>Welcome!</h1>
          {% if user.is_authenticated %}
              <h2>Hello {{ user }}</h2>
              <h2>Go <a href="{%url 'home' %}">Home?</a></h2>
              <h2>Track a <a href="{% url 'add' %}">New Food?</a></h2>
          {% else %}
              <h2>Register or Login if you'd like to</h2>
          {% endif %}
        </div>
      </div>
      {% endblock %}
    </div><!-- /.container -->

EatMoreFood/food/mpjct/templates/mpjct/login.html
{% extends 'mpjct/base.html' %}
<!DOCTYPE html>


<html lang="en">

<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
  <meta name="description" content="Food App Login">
  <meta name="author" content="Codejoy">
  {% block title %}
  <title>Food App Login</title>
  {% endblock %}
</head>

{% block body_block %}
  <div class="container">
    <div class="jumbotron">
      <h1>Login here :</h1>
<form method="post" action="{% url 'mpjct:user_login' %}">
          {% csrf_token %}
          <label for="username">Username:</label>
          <input type="text" name="username" placeholder="Username">
<label for="password">Password:</label>
          <input type="password" name="password" placeholder="Password">
<input type="submit" name="" value="Login">
</form>
</div>
  </div>
{% endblock %}
</html>

EatMoreFood/food/mpjct/templates/mpjct/signup.html
{% extends "mpjct/base.html" %}
{% load staticfiles %}
<html lang="en"><head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="Eat More Food Register">
    <meta name="author" content="Chris Asp">
{% block title %}
    <title>Register</title>
    {% endblock %}
{% block body_block %}
  <div class="container">
    <div class="jumbotron">
      {% if registered %}
        <h1>Thank you for registering!</h1>
      {% else %}
        <h1>Register Here</h1>
        <h3>Just fill out the form.</h3>
<form enctype="multipart/form-data" method="POST">
          {% csrf_token %}
          {{ user_form.as_p }}
          {{ profile_form.as_p }}
          <input type="submit" name="" value="signup">
        </form>

      {% endif %}
    </div>
  </div>
{% endblock %}